"""Hessa - local web server of the tutoring centre.

Runs with the Python standard library only (no pip install needed).
Installed with Hessa-Setup.exe (portable: start.bat); every PC on the network can then open the address
printed in the console window. Everybody must log in; what each user may see and
do is set by the administrator (Users page) and checked here for every request.
"""
import hashlib
import html

import json
import logging
import logging.handlers
import mimetypes
import os
import socket
import sys
import threading
import time
import traceback
import uuid
import webbrowser
from datetime import datetime
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, quote, unquote, urlparse

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)  # the portable (embedded) Python does not add the script folder itself

import backup as backup_mod  # noqa: E402
import xlsx  # noqa: E402
from auth import ADMIN_PERMS, ALL, PERMISSIONS, AuthError, Forbidden  # noqa: E402
import center  # noqa: E402
import formats  # noqa: E402
import gateway_client as gwc  # noqa: E402
import store as store_mod  # noqa: E402
from store import BadRequest, Conflict, now  # noqa: E402
from upgrade import DataFromNewerVersion, UpgradeVerificationFailed, check_now  # noqa: E402
from sync import SyncService  # noqa: E402
from system import System, lock_data  # noqa: E402

ROOT = os.path.dirname(HERE)  # program files (web pages); in the installed program they are built into Hessa.exe (_assets)
HOME = os.environ.get('HS_HOME') or ROOT  # config.json, data and backups: %ProgramData%\Hessa when installed
CONFIG_PATH = os.environ.get('HS_CONFIG') or os.path.join(HOME, 'config.json')
try:
    from _assets import ASSETS  # noqa: E402 - generated by tools/make_assets.py for the installed program
except ImportError:
    ASSETS = None
from version import COPYRIGHT, DEVELOPER, LICENSE_NOTE, PRODUCT, VERSION  # noqa: E402
DEFAULT_CONFIG = {
    'port': 8095,
    'host': '0.0.0.0',
    'data_dir': 'data',
    'backup_dir': 'backups',
    'extra_backup_dirs': [],
    'backup_interval_hours': 6,
    'keep_auto_backups': 200,
    'max_upload_mb': 50,
    'open_browser': True,
    'session_idle_minutes': 30,
    'session_max_hours': 12,
    'max_failed_logins': 5,
    'lockout_minutes': 15,
    'min_password_length': 8,
    'device_name': '',
    'sync_port': 8463,
    'sync_interval_seconds': 5,
    'peer_addresses': {},
}
STATIC = {'/': 'index.html', '/index.html': 'index.html'}
STATIC_DIRS = ('/css/', '/js/', '/lib/', '/fonts/')
STATIC_EXT = {'.html', '.js', '.css', '.svg', '.png', '.ico', '.woff', '.woff2', '.map', '.json'}
UPLOAD_EXT = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.heic', '.pdf', '.doc', '.docx', '.xls', '.xlsx',
              '.ppt', '.pptx', '.txt', '.csv', '.zip'}
IMAGE_EXT = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.heic'}
INLINE_EXT = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.pdf'}
TYPES = {'.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.html': 'text/html; charset=utf-8',
         '.json': 'application/json', '.svg': 'image/svg+xml', '.webp': 'image/webp', '.heic': 'image/heic',
         '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
         '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}


def load_config():
    cfg = dict(DEFAULT_CONFIG)
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, encoding='utf-8') as f:
            cfg.update(json.load(f))
    else:
        with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
            json.dump(cfg, f, indent=2)
    return cfg


def set_backup_folder(folder):
    """Choose (or with '' remove) the second backup folder of this PC. Stored in config.json of this PC only."""
    if folder:
        folder = os.path.normpath(folder)
        if backup_mod.network_folder(folder):
            raise BadRequest('Choose a USB drive or another disk of this PC, not a network folder (the backups contain the passwords).')
        if not os.path.isabs(folder):
            raise BadRequest('Type the full folder, for example E:\\Hessa-Backups.')
        inside = [os.path.normcase(os.path.realpath(d)) for d in (HOME, DATA_DIR, BACKUPS.dir)]
        f = os.path.normcase(os.path.realpath(folder))
        if any(f == d or f.startswith(d + os.sep) for d in inside):
            raise BadRequest('Choose a folder on another disk or a USB drive, not inside the program data.')
        try:
            os.makedirs(folder, exist_ok=True)
            test = os.path.join(folder, '.to-write-test')
            with open(test, 'w') as fh:
                fh.write('ok')
            os.remove(test)
        except OSError:
            raise BadRequest('This folder cannot be used (not found or no permission to write). Check the drive and try again.')
    dirs = ([folder] if folder else []) + [d for d in CFG.get('extra_backup_dirs', [])[1:] if d]  # the screen sets the first one
    try:
        cfg = {}
        if os.path.exists(CONFIG_PATH):
            with open(CONFIG_PATH, encoding='utf-8') as fh:
                cfg = json.load(fh)
        cfg['extra_backup_dirs'] = dirs
        tmp = CONFIG_PATH + '.tmp'
        with open(tmp, 'w', encoding='utf-8') as fh:
            json.dump(cfg, fh, indent=2)
        os.replace(tmp, CONFIG_PATH)
    except (OSError, ValueError):
        raise BadRequest('The setting could not be saved (config.json is damaged or cannot be written).')
    CFG['extra_backup_dirs'] = dirs
    BACKUPS.extra = [resolve(d) for d in dirs]
    BACKUPS.last_error = ''


def resolve(p):
    return p if os.path.isabs(p) else os.path.join(HOME, p)


CFG = load_config()
DATA_DIR = resolve(CFG['data_dir'])
UPLOADS = os.path.join(DATA_DIR, 'uploads')
os.makedirs(UPLOADS, exist_ok=True)
os.makedirs(os.path.join(DATA_DIR, 'logs'), exist_ok=True)

log = logging.getLogger('hessa')
log.setLevel(logging.INFO)
_fh = logging.handlers.RotatingFileHandler(os.path.join(DATA_DIR, 'logs', 'server.log'), maxBytes=5 * 1048576, backupCount=20, encoding='utf-8')
_fh.setFormatter(logging.Formatter('%(asctime)s %(levelname)s %(message)s'))
log.addHandler(_fh)


def say(msg):
    log.info(msg)
    print(f'[{datetime.now():%H:%M:%S}] {msg}', flush=True)


INSTANCE = lock_data(DATA_DIR)  # taken before anything touches the data


def stop_with_message(text):
    """Hessa cannot start safely: say why where the person can see it (the installed program has no console), then stop."""
    say('NOT STARTED: ' + text)
    try:
        os.makedirs(os.path.join(DATA_DIR, 'logs'), exist_ok=True)
        with open(os.path.join(DATA_DIR, 'logs', 'STARTUP_PROBLEM.txt'), 'w', encoding='utf-8') as f:
            f.write(f'{datetime.now():%Y-%m-%d %H:%M:%S}\n{text}\n')
    except OSError:
        pass
    try:
        if os.name == 'nt':
            import ctypes
            ctypes.windll.user32.MessageBoxW(0, text, 'Hessa', 0x10)
    except Exception:  # noqa: BLE001 - the log line above is already written
        pass
    raise SystemExit(3)


if INSTANCE:
    try:
        SYSTEM = System(DATA_DIR, CFG, UPLOADS, resolve(CFG['backup_dir']), [resolve(d) for d in CFG['extra_backup_dirs']], log=say)
    except (DataFromNewerVersion, UpgradeVerificationFailed) as e:
        stop_with_message(str(e))
    try:
        os.remove(os.path.join(DATA_DIR, 'logs', 'STARTUP_PROBLEM.txt'))  # a good start: the old message is no longer true
    except OSError:
        pass
    STORE, AUTH, BACKUPS, JOURNAL, NODE = SYSTEM.store, SYSTEM.auth, SYSTEM.backups, SYSTEM.journal, SYSTEM.node
    SYNC = SyncService(SYSTEM, CFG, UPLOADS, log=say)
    SECRETS = gwc.Secrets(os.path.join(DATA_DIR, 'gateway.json'))
else:
    SYSTEM = STORE = AUTH = BACKUPS = JOURNAL = NODE = SYNC = SECRETS = None
GATE = None
formats.OFFICE_TMP = os.path.join(DATA_DIR, 'tmp')
OFFICE_STATE = formats.office_state()      # is Microsoft Excel / Word on this PC? (decided once at start)


def store_bytes(data, ext, user='gateway', ip='', user_id=''):
    """Save bytes content-addressed in the uploads folder and register the file. Returns (path as the pages use it, sha256)."""
    sha = hashlib.sha256(data).hexdigest()
    os.makedirs(os.path.join(UPLOADS, 'cas'), exist_ok=True)
    path = os.path.join(UPLOADS, 'cas', sha + ext)
    if not os.path.exists(path):
        tmp = os.path.join(UPLOADS, 'cas', f'.{sha}.{uuid.uuid4().hex[:8]}.tmp')
        with open(tmp, 'wb') as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    src = f'/files/cas/{sha}{ext}'
    STORE.record_file(src, sha, len(data), mimetypes.guess_type(path)[0] or '', user, ip, user_id)
    return src, sha


if INSTANCE:
    GATE = gwc.GatewaySync(STORE, JOURNAL, NODE.id, SECRETS, store_bytes, log_fn=say)
PLACEHOLDER = (b'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 200"><rect width="320" height="200" fill="#eef1f5"/>'
               b'<text x="160" y="96" font-family="Segoe UI,Arial" font-size="15" text-anchor="middle" fill="#6b7785">Photo is being copied</text>'
               b'<text x="160" y="118" font-family="Segoe UI,Arial" font-size="12" text-anchor="middle" fill="#8a95a3">from another PC\u2026</text></svg>')
COOKIE = 'hs_sid'
ABOUT = {'product': PRODUCT, 'version': VERSION, 'developer': DEVELOPER, 'copyright': COPYRIGHT, 'license': LICENSE_NOTE,
         'installed': ASSETS is not None}
LOCAL_IPS = ('127.0.0.1', '::1', '::ffff:127.0.0.1')
CSP = ("default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; "
       "connect-src 'self' data: blob:; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'")
PERM_LABEL = {p: label for _, ps in PERMISSIONS for p, label in ps}
REPORT_PERMS = [p for p in ALL if p.startswith('report.')] + ['excel.export', 'logs.view', 'logs.activity', 'logs.security']
ENTITY_TITLE = {'subjects': 'subjects', 'rooms': 'rooms', 'teachers': 'teachers', 'students': 'students', 'groups': 'groups',
                'enrollments': 'enrolments', 'sessions': 'sessions', 'attendance': 'attendance', 'payments': 'receipts',
                'shifts': 'cash shifts', 'expenses': 'expenses', 'materials': 'handouts', 'exams': 'exams', 'marks': 'marks',
                'followups': 'follow-ups', 'settlements': 'settlements', 'settings': 'settings'}
OP_WORD = {'insert': 'add', 'update': 'change', 'delete': 'delete'}
SHARED_LISTS = ('settings', 'subjects', 'rooms', 'students')  # not limited to a teacher
DISCOUNT_FIELDS = {'discountPct', 'discountReason', 'exempt'}
SYSTEM_ONLY = ('data.import',)  # money, attendance, shifts and settlements are written by the server's own operations only


def required(entity, op, changed):
    """The permissions (any one of them is enough) needed for one saved change made in a page (generic save)."""
    if entity == 'students':
        if op == 'delete':
            return ('students.delete',)
        if set(changed) & DISCOUNT_FIELDS and op == 'update':
            return ('students.discount',)
        return ('students.manage',)
    return {
        'subjects': {'insert': ('rooms.manage',), 'update': ('rooms.manage',), 'delete': ('rooms.manage',)},
        'rooms': {'insert': ('rooms.manage',), 'update': ('rooms.manage',), 'delete': ('rooms.manage',)},
        'teachers': {'insert': ('teachers.manage',), 'update': ('teachers.manage',), 'delete': ('teachers.manage',)},
        'groups': {'insert': ('groups.manage',), 'update': ('groups.manage',), 'delete': ('groups.manage',)},
        'enrollments': {'insert': ('students.manage', 'students.transfer'), 'update': ('students.transfer',), 'delete': ('students.transfer',)},
        'sessions': {'insert': ('attendance.mark',), 'update': ('attendance.mark',), 'delete': ('attendance.edit',)},
        'materials': {'insert': ('materials.manage',), 'update': ('materials.manage',), 'delete': ('materials.manage',)},
        'exams': {'insert': ('exams.manage',), 'update': ('exams.manage',), 'delete': ('exams.manage',)},
        'marks': {'insert': ('marks.enter',), 'update': ('marks.enter',), 'delete': ('marks.enter',)},
        'followups': {'insert': ('followup.log',), 'update': ('followup.log',), 'delete': ('followup.log',)},
        'attendance': {'insert': SYSTEM_ONLY, 'update': SYSTEM_ONLY, 'delete': SYSTEM_ONLY},
        'payments': {'insert': SYSTEM_ONLY, 'update': SYSTEM_ONLY, 'delete': SYSTEM_ONLY},
        'expenses': {'insert': SYSTEM_ONLY, 'update': SYSTEM_ONLY, 'delete': SYSTEM_ONLY},
        'shifts': {'insert': SYSTEM_ONLY, 'update': SYSTEM_ONLY, 'delete': SYSTEM_ONLY},
        'settlements': {'insert': SYSTEM_ONLY, 'update': SYSTEM_ONLY, 'delete': SYSTEM_ONLY},
        'settings': {'insert': ('settings.edit',), 'update': ('settings.edit',), 'delete': ('settings.edit',)},
    }[entity][op]


def commit_guard(u):
    """Checks every change of a save against the user's permissions and trip categories."""
    perms, scope = set(u['perms']), (None if u['scopes'] is None else set(u['scopes']))

    def guard(changes, force):
        if force:  # replaces everything: import, load sample data, delete all sample data
            if 'data.import' not in perms or scope is not None:
                raise Forbidden('Only a user with the permission "' + PERM_LABEL['data.import'] + '" for all teachers can replace all data.')
            return
        for c in changes:
            e, op, sc = c['entity'], c['op'], c['scope']
            if scope is not None and e not in SHARED_LISTS and not {sc, c.get('scope_before', sc)} <= scope:
                raise Forbidden('You are limited to certain teachers and cannot add new ones.' if e == 'teachers' and op == 'insert'
                                else 'You can only change the work of the teachers assigned to you.')
            if e in ('students', 'teachers') and set(c['changes']) & {'mobile', 'parentMobile', 'parentMobile2'} and 'contacts.view' not in perms:
                raise Forbidden('Contact details require the permission to view contacts.')
            need = required(e, op, c['changes'])
            if not perms.intersection(need):
                raise Forbidden(f'You are not allowed to {OP_WORD[op]} {ENTITY_TITLE[e]}. Ask the administrator for the permission "{PERM_LABEL[need[0]]}".')
    return guard


def system_status(u):
    """What the server knows about its own health, cut down to what this user may act on (an empty dict for everybody else).
    Cheap reads only: it is asked by the overview every thirty seconds."""
    out = {}
    perms = set(u['perms'])
    if perms & {'backups.manage', 'backups.restore'}:
        listed = BACKUPS.list()
        with STORE.lock:
            has_data = STORE.conn.execute('SELECT 1 FROM students WHERE deleted=0 LIMIT 1').fetchone() is not None
        out['backup'] = {'last': listed[0]['time'] if listed else None, 'folders': len(BACKUPS.extra), 'error': BACKUPS.last_error,
                         'has_data': has_data, 'unsaved': STORE.version() != BACKUPS.last_version}
    if 'users.manage' in perms:
        summary = SYNC.summary()
        roster = [n for n in JOURNAL.roster().values() if n.get('status') == 'active']
        verify = JOURNAL.meta('last_verify') or {}
        with STORE.lock:
            conflicts = STORE.conn.execute('SELECT COUNT(*) FROM sync_flags').fetchone()[0]
        out['sync'] = {'state': summary.get('state'), 'problems': summary.get('problems', 0), 'online': summary.get('online', 0), 'multi': len(roster) > 1,
                       'authority': NODE.is_authority, 'key_saved': bool(JOURNAL.meta('key_saved')), 'conflicts': conflicts,
                       'verify_at': verify.get('ts'), 'verify_ok': verify.get('ok') if verify else None,
                       'pcs': len(roster)}
    if 'gateway.manage' in perms:
        out['gateway'] = {'configured': bool(SECRETS.configured)}
    return out


def lan_urls(port):
    urls = [f'http://{socket.gethostname()}:{port}/']
    try:
        for ip in socket.gethostbyname_ex(socket.gethostname())[2]:
            if not ip.startswith('127.'):
                urls.append(f'http://{ip}:{port}/')
    except OSError:
        pass
    return urls


def site_names():
    """System name and short name for the login screen (shown before anybody is logged in)."""
    out = {}
    try:
        with STORE.lock:
            for k, v in STORE.conn.execute("SELECT id, value FROM settings WHERE id IN ('systemName', 'logoText', 'factory')"):
                try:
                    v = json.loads(v)
                except (TypeError, ValueError):
                    pass
                if isinstance(v, str) and v.strip():
                    out[k] = v.strip()[:80]
    except Exception:  # noqa: BLE001 - only cosmetics for the login screen
        pass
    return out


class NotLoggedIn(Exception):
    pass


def is_admin(u):
    """Administrator = may manage users. Monitoring, devices and conflicts need this, checked on every request."""
    return bool(u) and 'users.manage' in u['perms']


FAILED = {}  # ip -> times of recent failed logins (this PC only)
FAILED_LOCK = threading.Lock()


def too_many_failures(ip, add=False):
    """More than 10 failed logins (password or link) from one address within a minute: refuse quickly for a while,
    without the slow password check and without filling the logs of every PC."""
    t = time.time()
    with FAILED_LOCK:
        recent = [x for x in FAILED.get(ip, []) if t - x < 60]
        if add:
            recent.append(t)
        if recent:
            FAILED[ip] = recent[-50:]
        else:
            FAILED.pop(ip, None)
        if len(FAILED) > 5000:  # never grow without limit
            FAILED.clear()
        return len(recent) > 10


class Handler(BaseHTTPRequestHandler):
    server_version = 'Hessa/1.0'
    protocol_version = 'HTTP/1.1'
    timeout = 120  # a connection that stays silent is closed
    u = None  # the logged-in user of this request (set by login_required)
    _read = False  # True once the request body was read

    # ------------------------------------------------------------ plumbing
    def log_message(self, fmt, *args):
        pass  # API calls are logged explicitly below; static files are not worth logging

    @property
    def user(self):
        return self.u['display'] if self.u else 'Not logged in'

    @property
    def log_path(self):
        """The address for logs: the secret part of a personal link is never written anywhere."""
        return '/k/…' if self.path.startswith('/k/') else self.path

    @property
    def ip(self):
        return self.client_address[0]

    @property
    def token(self):
        for part in (self.headers.get('Cookie') or '').split(';'):
            k, _, v = part.strip().partition('=')
            if k == COOKIE:
                return v
        return ''

    def login_required(self, touch=True):
        self.u = AUTH.session(self.token, self.ip, touch)
        if not self.u:
            raise NotLoggedIn()
        return self.u

    def can(self, *perms):
        return bool(self.u) and any(p in self.u['perms'] for p in perms)

    def need(self, *perms):
        if not self.can(*perms):
            raise Forbidden('You do not have permission for this. Ask the administrator for: "' + PERM_LABEL[perms[0]] + '".')

    def send(self, code, body=b'', ctype='application/json', headers=None):
        if isinstance(body, (dict, list)):
            body = json.dumps(body, ensure_ascii=False).encode('utf-8')
        elif isinstance(body, str):
            body = body.encode('utf-8')
        self.send_response(code)
        unread = self.command == 'POST' and not self._read and int(self.headers.get('Content-Length') or 0)
        if code >= 400 or unread:  # the request body may be unread - don't reuse this connection
            self.close_connection = True
            self.send_header('Connection', 'close')
        self.send_header('Content-Type', ctype)
        self.send_header('Content-Length', str(len(body)))
        self.send_header('X-Content-Type-Options', 'nosniff')
        self.send_header('X-Frame-Options', 'DENY')
        self.send_header('Referrer-Policy', 'same-origin')
        if ctype.startswith('text/html'):
            self.send_header('Content-Security-Policy', CSP)
        headers = dict(headers or {})
        if self.path.startswith('/api/'):
            headers.setdefault('Cache-Control', 'no-store')
        for k, v in headers.items():
            self.send_header(k, v)
        self.end_headers()
        if self.command != 'HEAD':
            self.wfile.write(body)

    def link_page(self, token):
        """Opening a personal link shows a tiny page that logs in by itself (js/quick.js). Logging in only happens with the
        POST from this page, so a program that merely looks at the link (a chat preview, a virus scanner) logs nobody in."""
        u = AUTH.link_user(token)
        ok = u and u['active'] and AUTH.link_allowed(u)
        title = PRODUCT
        now_in = AUTH.session(self.token, self.ip, touch=False) if ok and self.token else None
        if now_in and now_in['id'] == u['id']:
            return self.send(303, b'', 'text/plain', {'Location': '/'})  # already logged in as this person
        if ok:
            name = html.escape(u['full_name'])
            label = (f'المتابعة باسم {name} · Continue as {name}' if now_in else 'افتح النظام · Open the system')
            form = f'<form id="{"ask" if now_in else "go"}" method="post" action="/k/{html.escape(token)}"><button type="submit">{label}</button></form>'
            if now_in:  # somebody else is logged in in this browser: never switch without asking
                other = html.escape(now_in['full_name'])
                body = (f'<h1>الرابط الشخصي لـ {name}</h1><p>هذا المتصفح مسجّل الآن باسم <b>{other}</b>. المتابعة تُخرج {other}.</p>'
                        f'<p class="en" dir="ltr">Personal link of {name}. This browser is signed in as <b>{other}</b>; continuing signs {other} out.</p>' + form +
                        f'<p class="small"><a href="/">البقاء باسم {other} · Stay as {other}</a></p>')
            else:
                body = (f'<h1>أهلًا {name}</h1><p>جارٍ فتح النظام لك…</p><p class="en" dir="ltr">Welcome, {name}. Opening the system for you…</p>' + form +
                        '<p class="small">هذا رابطك الشخصي، لا تعطه لأحد: من معه الرابط يعمل باسمك.<br><span dir="ltr">This is your personal link. '
                        'Do not give it to anybody - whoever has it works under your name.</span></p><script src="/js/quick.js"></script>')
        else:
            body = ('<h1>هذا الرابط لم يعد يعمل</h1><p>اطلب رابطك الجديد من المسؤول، أو <a href="/">ادخل باسم المستخدم وكلمة المرور</a>.</p>'
                    '<p class="en" dir="ltr">This link does not work any more. Ask the administrator for your new link, or '
                    '<a href="/">sign in with your user name and password</a>.</p>')
        page = (f'<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
                f'<title>{html.escape(title)}</title><style>body{{font-family:system-ui,Segoe UI,Arial,'
                'sans-serif;background:#f3f5f8;color:#1b2533;display:flex;min-height:90vh;align-items:center;justify-content:center;margin:0 16px}'
                'main{background:#fff;border-radius:12px;padding:28px 32px;max-width:440px;box-shadow:0 4px 18px #0001;text-align:center}'
                'h1{font-size:1.35rem}button{font-size:1.05rem;padding:10px 26px;border:0;border-radius:8px;background:#1f6feb;color:#fff;cursor:pointer}'
                '.small{font-size:.85rem;color:#5b6675;margin-top:18px}.en{color:#5b6675;font-size:.9rem}</style></head><body><main>' + body + '</main></body></html>')
        return self.send(200 if ok else 404, page, 'text/html; charset=utf-8', {'Cache-Control': 'no-store'})

    def set_session(self, token):
        return {'Set-Cookie': f'{COOKIE}={token}; Path=/; HttpOnly; SameSite=Strict'}

    def clear_session(self):
        return {'Set-Cookie': f'{COOKIE}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'}

    def body(self, limit=20 * 1048576):
        raw = self.headers.get('Content-Length') or '0'
        if not raw.isdigit():
            raise BadRequest('Invalid request length')
        n = int(raw)
        if n > limit:
            raise BadRequest(f'Request too large ({n // 1048576} MB)')
        self._read = True
        return self.rfile.read(n) if n else b''

    def json_body(self):
        raw = self.body(200 * 1048576 if self.u else 65536)  # before logging in only small requests
        return json.loads(raw.decode('utf-8')) if raw else {}

    def denied(self, msg):
        AUTH.log(self.user, self.ip, 'access-denied', self.log_path.split('?')[0], msg)
        try:
            STORE.log_activity(self.user, self.ip, [{'type': 'denied', 'action': self.log_path.split('?')[0], 'detail': msg}])
        except Exception:
            pass

    def handle_safely(self, fn):
        try:
            fn()
        except NotLoggedIn:
            self.send(401, {'error': 'Please log in.', 'login': True}, headers=self.clear_session())
        except Forbidden as e:
            log.info('DENIED %s %s %s', self.user, self.log_path, e)
            self.denied(str(e))
            self.send(403, {'error': str(e)})
        except AuthError as e:
            self.send(400, {'error': str(e)})
        except Conflict as e:
            log.info('CONFLICT %s %s %s', self.user, self.log_path, e)
            self.send(409, {'error': str(e)})
        except (BadRequest, ValueError) as e:
            log.info('BAD REQUEST %s %s %s', self.user, self.log_path, e)
            body = {'error': str(e)}
            if isinstance(e, center.Problem):
                body.update({'key': e.key, 'vars': e.vars})
            self.send(400, body)
        except (ConnectionError, BrokenPipeError):
            pass
        except Exception as e:
            tb = traceback.format_exc()
            log.error('ERROR %s %s\n%s', self.user, self.log_path, tb)
            try:
                STORE.log_activity(self.user, self.ip, [{'type': 'server-error', 'action': self.log_path, 'detail': tb[-1900:]}])
            except Exception:
                pass
            self.send(500, {'error': f'Server error: {e}'})

    # ------------------------------------------------------------ routing
    def do_HEAD(self):
        self.do_GET()

    def do_GET(self):
        self.u = None
        self.handle_safely(self._get)

    def do_POST(self):
        self.u, self._read = None, False
        self.handle_safely(self._post)

    def me(self):
        u = self.u
        return {**AUTH.public(u), 'display': u['display'], 'permissions': PERMISSIONS, 'adminPerms': sorted(ADMIN_PERMS),
                'sessionIdleMinutes': CFG['session_idle_minutes'], 'minPasswordLength': AUTH.min_len, 'admin': is_admin(u), 'viaLink': bool(u.get('via_link')),
                'node': {'id': NODE.id, 'name': NODE.name, 'role': NODE.role, 'authority': NODE.is_authority}}

    def need_all_scopes(self):
        if self.u['scopes'] is not None:
            raise Forbidden('This shows the whole centre. It is only for users who work with all teachers.')

    def ctx(self, guard=False):
        return center.Ctx(STORE, JOURNAL, NODE.id, self.user, self.ip, self.u['id'], self.u['scopes'], self.u['perms'],
                          commit_guard(self.u) if guard else None)

    def need_admin(self):
        if not is_admin(self.u):
            raise Forbidden('Only an administrator can open this.')

    def node_status(self):
        j = JOURNAL.meta('join')
        return {'role': NODE.role, 'name': NODE.name, 'id': NODE.id, 'moved': NODE.moved,
                'join': {'confirm': j['confirm'], 'authority': j.get('authority')} if j and NODE.role == 'unconfigured' else None}

    def _get(self):
        url = urlparse(self.path)
        p, qs = url.path, {k: v[0] for k, v in parse_qs(url.query).items()}
        if p in STATIC:
            return self.serve_static(STATIC[p])
        if p.startswith(STATIC_DIRS):
            return self.serve_static(p.lstrip('/'))
        if p.startswith('/k/'):
            return self.link_page(p[3:])
        if p == '/api/auth/status':
            u = AUTH.session(self.token, self.ip, touch=False)
            self.u = u
            return self.send(200, {'hasUsers': AUTH.has_users(), 'local': self.ip in LOCAL_IPS, 'me': self.me() if u else None,
                                   'node': self.node_status(), 'about': {**ABOUT, **site_names()}})
        if p == '/api/join/status':
            if self.ip not in LOCAL_IPS or AUTH.has_users() and NODE.role != 'member':
                raise Forbidden('Only on this PC itself.')
            return self.send(200, {**SYNC.join_progress(), 'hasUsers': AUTH.has_users()})

        self.login_required(touch=p != '/api/version')
        if p == '/api/me':
            return self.send(200, self.me())
        if p == '/api/state':
            full = qs.get('all') == '1' and self.u['scopes'] is None and self.can('money.view')
            return self.send(200, {**self.state_filter(STORE.state(self.u['scopes'], None if full else store_mod.WINDOW_DAYS)), 'gateway': bool(SECRETS.configured),
                                   'office': OFFICE_STATE, 'node': {'id': NODE.id, 'letter': self.ctx().letter()}})
        if p == '/api/delta':
            d = STORE.delta(int(qs.get('since') or -1), self.u['scopes'])
            return self.send(200, self.state_filter(d) if d is not None else {'full': True})
        if p.startswith('/api/c/'):
            return self.center_get(p[len('/api/c/'):], qs)
        if p == '/api/version':
            return self.send(200, {'version': STORE.version(), 'me': self.u['ver'], 'mustChange': bool(self.u['must_change']),
                                   'sync': SYNC.summary(), 'gateway': SECRETS.configured})
        if p in ('/api/gateway', '/api/gateway/code', '/api/gateway/secret'):
            self.need('gateway.manage')
            self.need_all_scopes()
            if p.endswith('/code') or p.endswith('/secret'):
                if not SECRETS.configured:
                    raise center.Problem('err.noGateway', 'Configure parent links first.')
                # the secret goes to Cloudflare once (docs/GATEWAY_SETUP.md); who looked at it is written in the security log
                AUTH.log(self.u['display'], self.ip, 'gateway-secret', 'gateway', 'Setup code shown' if p.endswith('/code') else 'Office secret shown')
                return self.send(200, {'code': SECRETS.setup_code()} if p.endswith('/code') else {'secret': SECRETS.data['officeSecret']})
            links = len(STORE.rows('students', "portal_hash IS NOT NULL AND portal_hash<>''"))
            return self.send(200, {**GATE.status(), 'links': links})
        if p == '/api/info':
            urls = lan_urls(CFG['port'])
            if not self.can('settings.view'):
                return self.send(200, {'urls': urls})
            db_size = sum(os.path.getsize(os.path.join(DATA_DIR, f)) for f in os.listdir(DATA_DIR) if f.startswith('center.db'))
            up_size = sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(UPLOADS) for f in fs)
            return self.send(200, {'urls': urls, 'dataDir': DATA_DIR, 'backupDir': BACKUPS.dir,
                                   'extraBackupDirs': BACKUPS.extra, 'dbSize': db_size, 'uploadsSize': up_size,
                                   'backupIntervalHours': CFG['backup_interval_hours'], 'lastBackupError': BACKUPS.last_error,
                                   'counts': STORE.counts(), 'serverTime': now()})
        if p == '/api/backups':
            self.need('backups.manage', 'backups.restore')
            return self.send(200, BACKUPS.list())
        if p == '/api/data-safety':  # what the last program update did to the data, and the safety copies it made
            self.need('backups.manage', 'backups.restore')
            return self.send(200, {**SYSTEM.upgrade.info(), 'program': VERSION})
        if p == '/api/backups/folder':
            self.need('backups.manage')
            return self.send(200, {'dirs': BACKUPS.extra, 'error': BACKUPS.last_error, 'local': self.ip in LOCAL_IPS,
                                   'admin': is_admin(self.u)})
        if p == '/api/trash':
            self.need('trash.restore')
            self.need_all_scopes()
            return self.send(200, STORE.trash())
        if p in ('/api/audit', '/api/activity'):
            self.need('logs.view' if p == '/api/audit' else 'logs.activity')
            if p == '/api/activity':
                self.need_admin()  # what other people clicked is forensic data: administrators only
            node = qs.get('node', '') if is_admin(self.u) else ''
            return self.send(200, STORE.query_log('audit' if p == '/api/audit' else 'activity', qs.get('q', ''), qs.get('user', ''),
                                                  qs.get('type', ''), qs.get('scope', ''), qs.get('from', ''), qs.get('to', ''),
                                                  max(1, min(1000, int(qs.get('limit', 200)))), max(0, int(qs.get('offset', 0))), self.u['scopes'], node,
                                                  admin=is_admin(self.u), contacts=self.can('contacts.view'),
                                                  entity=qs.get('entity', ''), rid=qs.get('id', '')))
        if p == '/api/security':
            self.need('logs.security')
            self.need_admin()
            return self.send(200, AUTH.query_log(qs.get('q', ''), qs.get('user', ''), qs.get('type', ''), qs.get('from', ''), qs.get('to', ''),
                                                 max(1, min(1000, int(qs.get('limit', 200)))), max(0, int(qs.get('offset', 0))), qs.get('node', '')))
        if p == '/api/devices':
            self.need_admin()
            return self.send(200, SYNC.overview())
        if p == '/api/quick-links':
            self.need_admin()
            return self.send(200, {'users': AUTH.link_list(), 'authority': NODE.is_authority,
                                   'authorityHint': '' if NODE.is_authority else AUTH.authority_hint(), 'urls': lan_urls(CFG['port'])})
        if p == '/api/devices/log':
            self.need_admin()
            with JOURNAL.lock:
                rows = [dict(r) for r in JOURNAL.conn.execute('SELECT * FROM sync_log ORDER BY id DESC LIMIT ?', (min(1000, int(qs.get('limit', 300))),))]
            return self.send(200, rows)
        if p == '/api/conflicts':
            self.need_admin()
            return self.send(200, self.conflict_list())
        if p == '/api/users':
            self.need('users.manage')
            return self.send(200, {'users': AUTH.list_users(), 'permissions': PERMISSIONS, 'profiles': AUTH.profiles(), 'adminPerms': sorted(ADMIN_PERMS),
                                   'authority': NODE.is_authority,
                                   'authorityHint': '' if NODE.is_authority else AUTH.authority_hint()})
        if p == '/api/export.xlsx':
            self.need('report.full')
            if self.u['scopes'] is not None:
                raise Forbidden('The complete export contains all teachers; you only have access to some of them.')
            data = xlsx.build(STORE.export_sheets(admin=is_admin(self.u) and self.can('logs.activity')))
            log.info('EXPORT full workbook by %s (%s)', self.user, self.ip)
            STORE.log_activity(self.user, self.ip, [{'type': 'export', 'action': 'Full Excel export', 'target': 'All data'}])
            return self.send(200, data, TYPES['.xlsx'], {'Content-Disposition': f'attachment; filename="Hessa_Full_Export_{datetime.now():%Y-%m-%d_%H%M}.xlsx"'})
        if p.startswith('/files/'):
            if os.path.splitext(p)[1].lower() not in IMAGE_EXT:
                self.need('files.download')
            return self.serve_file(UPLOADS, p[len('/files/'):], upload=True, src=p)
        self.send(404, {'error': 'Not found'})

    def _post(self):
        p = urlparse(self.path).path
        qs = {k: v[0] for k, v in parse_qs(urlparse(self.path).query).items()}
        origin = self.headers.get('Origin')
        if origin and urlparse(origin).netloc != self.headers.get('Host'):
            raise Forbidden('Request from another web site was blocked.')

        # ---------------- no login needed
        if p.startswith('/k/'):  # personal link: the page below sends this by itself
            if too_many_failures(self.ip):
                raise AuthError('Too many attempts. Wait a minute and try again.')
            try:
                token, u = AUTH.link_login(p[3:], self.ip, self.headers.get('User-Agent', ''))
            except AuthError:
                too_many_failures(self.ip, add=True)
                time.sleep(0.6)
                return self.link_page(p[3:])
            if self.token:
                AUTH.logout(self.token, None, self.ip)  # whoever was logged in in this browser before
            say(f'Login with personal link: {u["display"]} ({self.ip})')
            return self.send(303, b'', 'text/plain', {'Location': '/', **self.set_session(token)})
        if p == '/api/auth/login':
            d = self.json_body()
            if too_many_failures(self.ip):
                raise AuthError('Too many wrong attempts from this computer. Wait a minute and try again.')
            try:
                token, u = AUTH.login(d.get('username'), d.get('password'), self.ip, self.headers.get('User-Agent', ''))
            except AuthError:
                too_many_failures(self.ip, add=True)
                time.sleep(0.6)  # slows down password guessing
                raise
            self.u = u
            say(f'Login: {u["display"]} ({self.ip})')
            return self.send(200, self.me(), headers=self.set_session(token))
        if p == '/api/join':
            if self.ip not in LOCAL_IPS or AUTH.has_users() or NODE.role != 'unconfigured':
                raise Forbidden('Joining is only possible on a new, not yet set up PC, on the PC itself.')
            d = self.json_body()
            try:
                return self.send(200, SYNC.join(d.get('address'), d.get('code'), d.get('name')))
            except ValueError as e:
                raise BadRequest(str(e))
        if p == '/api/join/probe':  # checks an address typed on the join screen
            if self.ip not in LOCAL_IPS or AUTH.has_users() or NODE.role != 'unconfigured':
                raise Forbidden('Only on a new, not yet set up PC, on the PC itself.')
            try:
                return self.send(200, SYNC.probe(self.json_body().get('address')))
            except ValueError as e:
                raise BadRequest(str(e))
        if p == '/api/join/discover':
            if self.ip not in LOCAL_IPS or AUTH.has_users() or NODE.role != 'unconfigured':
                raise Forbidden('Only on a new, not yet set up PC, on the PC itself.')
            return self.send(200, {'found': SYNC.discover()})
        if p == '/api/join/cancel':
            if self.ip not in LOCAL_IPS or NODE.role != 'unconfigured':
                raise Forbidden('Not possible.')
            JOURNAL.set_meta('join', None)
            return self.send(200, {'ok': True})
        if p == '/api/node/moved':
            if self.ip not in LOCAL_IPS or not NODE.moved:
                raise Forbidden('Only on this PC itself.')
            choice = self.json_body().get('choice')
            if choice == 'same':
                NODE.confirm_same_machine()
                AUTH.log('This PC', self.ip, 'node-confirmed', NODE.name, 'Confirmed on this PC: same computer as before (name or network card changed)')
                SYNC.kick()
                return self.send(200, {'ok': True})
            if choice == 'new':
                with open(os.path.join(NODE.dir, 'RESET_REQUESTED'), 'w') as f:
                    f.write(now())
                return self.send(200, {'ok': True, 'restart': True})
            raise BadRequest('Choose same or new')
        if p == '/api/auth/setup':
            if self.ip not in LOCAL_IPS:
                raise Forbidden('The first administrator account can only be created on the PC with the program itself.')
            d = self.json_body()
            AUTH.setup(d.get('username'), d.get('full_name'), d.get('password'), self.ip)
            token, self.u = AUTH.login(d.get('username'), d.get('password'), self.ip, self.headers.get('User-Agent', ''))
            say(f'Administrator account created: {self.u["display"]}')
            return self.send(200, self.me(), headers=self.set_session(token))
        if p == '/api/auth/logout':
            u = AUTH.session(self.token, self.ip, touch=False)
            AUTH.logout(self.token, u, self.ip)
            return self.send(200, {'ok': True}, headers=self.clear_session())

        # ---------------- logged in
        self.login_required()
        if p == '/api/auth/password':
            d = self.json_body()
            AUTH.change_password(self.u, d.get('old'), d.get('new'), self.ip, self.token)
            self.u = AUTH.get(self.u['id'])
            return self.send(200, self.me())
        if p == '/api/log':
            d = self.json_body()
            events = [{**e, 'user': self.user} for e in (d.get('events') or []) if isinstance(e, dict)]  # never trust a name sent by the page
            STORE.log_activity(self.user, self.ip, events)
            return self.send(200, {'ok': True})
        if self.u['must_change']:
            raise Forbidden('Please change your temporary password first.')
        if NODE.moved:
            raise Forbidden('This PC needs a decision first: its data folder seems to come from another PC. Open the system on this PC itself.')
        if p == '/api/commit':
            d = self.json_body()
            label = str(d.get('label') or 'Change')[:200]
            force = bool(d.get('force'))
            if force:
                self.need('data.import')
                if STORE.counts().get('Students'):
                    BACKUPS.create('pre-import')
            if any(isinstance(o, dict) and 'resolve' in o for o in (d.get('ops') or []) if isinstance(d.get('ops'), list)):
                raise Forbidden('Conflicts are decided only in Devices & Sync by an administrator.')
            raw_ops = d.get('ops')
            if isinstance(raw_ops, list) and any(isinstance(o, dict) and o.get('e') in ('payments', 'expenses', 'shifts', 'settlements', 'attendance') for o in raw_ops):
                raise Forbidden('Use the dedicated centre operation for attendance and money records.')
            with STORE.lock:
                if not force and not self.can('contacts.view') and isinstance(raw_ops, list):
                    for op in raw_ops:
                        if isinstance(op, dict) and op.get('e') in ('students', 'teachers') and op.get('op') == 'put' and isinstance(op.get('row'), dict):
                            old = STORE.row(op['e'], op.get('id')) or {}
                            for key in ('mobile', 'parentMobile', 'parentMobile2'):
                                if key not in op['row'] and key in old:
                                    op['row'][key] = old[key]
                ops = raw_ops if force else center.normalize_ops(STORE, raw_ops, self.ctx().pc_index())
                res = STORE.commit(self.user, self.ip, label, ops, force, guard=commit_guard(self.u), user_id=self.u['id'])
            log.info('COMMIT %s (%s) "%s" %s changes', self.user, self.ip, label, res['changes'])
            return self.send(200, res)
        if p == '/api/import/preview':
            self.need('students.manage')
            self.need('contacts.view')
            data, name = self.body(30 * 1048576), qs.get('name', '')[:120]
            return self.send(200, center.import_preview(STORE, data, name, qs.get('grade', ''), qs.get('group', ''), self.u.get('scopes')))
        if p.startswith('/api/c/'):
            return self.center_post(p[len('/api/c/'):], self.json_body())
        if p.startswith('/api/gateway/'):
            self.need('gateway.manage')
            self.need_all_scopes()
            d = self.json_body()
            action = p[len('/api/gateway/'):]
            try:
                if action == 'save':
                    SECRETS.set_url(d.get('url'))
                    poll = int(d.get('pollSeconds') or 60)
                    SECRETS.data['pollSeconds'] = min(600, max(15, poll))
                    SECRETS.save()
                elif action == 'generate':
                    if SECRETS.configured and not d.get('replace'):
                        raise center.Problem('gw.err.exists', 'Secrets already exist. Replacing them stops every existing parent link until the gateway is updated.')
                    SECRETS.generate()
                    GATE.pushed.clear()
                elif action == 'code':
                    SECRETS.from_code(d.get('code'))
                    GATE.pushed.clear()
                elif action == 'test':
                    st = GATE.client().status()
                    return self.send(200, {'ok': True, **st})
                elif action in ('send', 'pull'):
                    GATE._pushed_version = None          # "Send now": every changed card goes out at once
                    GATE.cycle()
                    return self.send(200, {**GATE.status(), 'links': len(STORE.rows('students', "portal_hash IS NOT NULL AND portal_hash<>''"))})
                else:
                    return self.send(404, {'error': 'Not found'})
            except gwc.GatewayError as e:
                # the round failed: remember why for the status line, and say it in the person's language
                GATE.stat['lastError'], GATE.stat['lastErrorKey'], GATE.stat['lastErrorVars'], GATE.stat['lastTry'] = str(e), e.key, e.vars, gwc._now()
                raise center.Problem(e.key, str(e), **e.vars)
            STORE.log_activity(self.user, self.ip, [{'type': 'security', 'action': 'Mailbox ' + action, 'target': 'gateway'}])
            GATE.kick()
            return self.send(200, GATE.status())
        if p == '/api/first-run':
            self.need('data.import')
            won = STORE.claim_first_run()
            if won:
                say(f'New database - sample data is being loaded by {self.user} ({self.ip})')
            return self.send(200, {'loadSample': won})
        if p == '/api/upload':
            self.need('settings.edit', 'data.import', 'students.manage')
            return self.upload(qs.get('name', 'file'))
        if p == '/api/xlsx':
            self.need(*REPORT_PERMS)
            d = self.json_body()
            data = xlsx.build([(s.get('name', 'Sheet'), s.get('head', []), s.get('rows', [])) for s in d.get('sheets', [])])
            name = ''.join(ch for ch in str(d.get('filename') or 'export') if ch.isalnum() or ch in ' _-.')[:80]
            return self.send(200, data, TYPES['.xlsx'], {'Content-Disposition': f'attachment; filename="{name}.xlsx"'})
        if p == '/api/backups':
            self.need('backups.manage')
            name = BACKUPS.create('manual')
            log.info('BACKUP manual by %s: %s', self.user, name)
            STORE.log_activity(self.user, self.ip, [{'type': 'backup', 'action': 'Backup created', 'target': name}])
            return self.send(200, {'name': name})
        if p == '/api/data-safety/check':  # "Check my data now": integrity of the databases and the whole signed history
            self.need('backups.manage')
            res = check_now(SYSTEM)
            STORE.log_activity(self.user, self.ip, [{'type': 'backup', 'action': 'Data check', 'target': 'ok' if res['ok'] else 'problems found'}])
            return self.send(200, res)
        if p == '/api/backups/folder':  # a second folder (USB drive, other disk) that gets a copy of every backup
            self.need('backups.manage')
            if not is_admin(self.u):
                raise Forbidden('Only an administrator can choose the backup folder.')
            if self.ip not in LOCAL_IPS:
                raise Forbidden('For safety, choose the backup folder on this PC itself.')
            folder = str(self.json_body().get('path') or '').strip().strip('"')
            set_backup_folder(folder)
            AUTH.log(self.u['display'], self.ip, 'backup-folder', folder or '-', 'Second backup folder set' if folder else 'Second backup folder removed')
            name = BACKUPS.create('manual') if folder else ''
            return self.send(200, {'ok': not BACKUPS.last_error, 'error': BACKUPS.last_error, 'name': name})
        if p == '/api/backups/restore':
            self.need('backups.restore')
            d = self.json_body()
            safety, res = BACKUPS.restore(d.get('name'), self.user, self.ip, self.u['id'])
            STORE.log_activity(self.user, self.ip, [{'type': 'restore', 'action': 'Restored backup', 'target': d.get('name'),
                                                      'detail': f'{res["changes"]} records brought back; safety backup before restore: {safety}'}])
            AUTH.log(self.user, self.ip, 'backup-restored', d.get('name'), f'{res["changes"]} records changed back; safety backup: {safety}')
            say(f'Backup {d.get("name")} restored by {self.user} ({self.ip}); {res["changes"]} records; previous data saved as {safety}')
            return self.send(200, {'ok': True, 'safety': safety, 'changes': res['changes']})
        if p == '/api/trash/restore':
            self.need('trash.restore')
            self.need_all_scopes()
            d = self.json_body()
            return self.send(200, STORE.restore_txn(self.user, self.ip, str(d.get('txn'))))
        if p == '/api/quick-links/set':
            self.need_admin()
            d = self.json_body()
            AUTH.link_set(self.u, self.ip, str(d.get('id')), bool(d.get('on')))
            return self.send(200, {'ok': True})
        if p.startswith('/api/devices/'):
            self.need_admin()
            d = self.json_body()
            action = p[len('/api/devices/'):]
            try:
                if action == 'export-key':  # the administrator key, protected by a passphrase, as a file for a USB stick
                    if self.ip not in LOCAL_IPS:
                        raise Forbidden('For safety, save the administrator key on the administrator PC itself.')
                    if not NODE.is_authority or NODE.info.get('backup'):
                        raise Forbidden('Only the administrator PC can save the administrator key.')
                    pw = str(d.get('passphrase') or '')
                    if len(pw) < 12:
                        raise BadRequest('The passphrase must have at least 12 characters.')
                    import nodectl
                    box = nodectl.seal(NODE.authority_seed, pw, {'cluster': NODE.info.get('cluster_id'), 'authority_pub': NODE.info.get('authority_pub'),
                                                                 'exported': now(), 'from': NODE.name})
                    JOURNAL.set_meta('key_saved', now())
                    AUTH.log(self.u['display'], self.ip, 'authority-exported', NODE.name, 'Administrator key saved as a file (passphrase protected)')
                    return self.send(200, box, headers={'Content-Disposition': 'attachment; filename="Hessa-administrator-key.json"'})
                if action == 'invite':
                    return self.send(200, SYNC.create_invite(self.user))
                if action == 'adding-open':   # the owner lets ONE new PC join (15 minutes) - the door is closed otherwise
                    return self.send(200, SYNC.open_adding(self.user))
                if action == 'adding-close':
                    SYNC.close_adding(self.user, 'closed by the administrator')
                    return self.send(200, {'ok': True})
                if action == 'decide':
                    SYNC.decide(str(d.get('id')), bool(d.get('approve')), self.u)
                elif action == 'update':
                    SYNC.update_node(str(d.get('id')), self.u, name=d.get('name'), address=d.get('address'))
                elif action == 'revoke':
                    SYNC.update_node(str(d.get('id')), self.u, revoke=True)
                elif action == 'backup':
                    SYNC.set_backup(str(d.get('id')), self.u, bool(d.get('on')))
                elif action == 'sync-now':
                    for st in SYNC.status.values():
                        st['fails'] = 0
                    SYNC.kick()
                elif action == 'verify':
                    rep = JOURNAL.verify(all_signatures=bool(d.get('all')))
                    AUTH.log(self.user, self.ip, 'integrity-check', 'history', 'OK' if rep['ok'] else f'{rep["problemCount"]} problem(s)')
                    return self.send(200, rep)
                elif action == 'ack':
                    JOURNAL.ack_alert(str(d.get('key')))
                else:
                    return self.send(404, {'error': 'Not found'})
            except PermissionError as e:
                raise Forbidden(str(e))
            except ValueError as e:
                raise BadRequest(str(e))
            return self.send(200, {'ok': True})
        if p == '/api/conflicts/resolve':
            self.need_admin()
            return self.send(200, self.resolve_conflict(self.json_body()))
        if p in ('/api/profiles/save', '/api/profiles/delete'):
            self.need('users.manage')
            d = self.json_body()
            if p.endswith('save'):
                return self.send(200, AUTH.save_profile(self.u, self.ip, d))
            AUTH.delete_profile(self.u, self.ip, str(d.get('id') or ''))
            return self.send(200, {'ok': True})
        if p.startswith('/api/users/'):
            self.need('users.manage')
            d = self.json_body()
            action = p[len('/api/users/'):]
            if action == 'save':
                return self.send(200, AUTH.save_user(self.u, self.ip, d))
            uid = str(d.get('id') or '')
            if action == 'reset':
                AUTH.reset_password(self.u, self.ip, uid, d.get('password'))
            elif action == 'unlock':
                AUTH.unlock(self.u, self.ip, uid)
            elif action == 'logout':
                AUTH.force_logout(self.u, self.ip, uid)
            elif action == 'delete':
                AUTH.delete_user(self.u, self.ip, uid)
            else:
                return self.send(404, {'error': 'Not found'})
            return self.send(200, {'ok': True})
        self.send(404, {'error': 'Not found'})

    # ------------------------------------------------------------ the centre (center.py)
    def center_get(self, action, qs):
        sc = self.u['scopes']
        if action == 'wa':
            self.need('messages.send')
            self.need('contacts.view')
            sid = qs.get('studentId', '')
            file = center.student_file(STORE, sid, sc)
            st = file['student']
            cfg = center.settings(STORE)
            lang = 'en' if qs.get('lang') == 'en' else 'ar'
            kind = qs.get('kind', 'monthly')
            templates = cfg.get('waTemplates') or {}
            text = (templates.get(kind) or {}).get(lang) or (center.WA_DEFAULTS.get(kind) or center.WA_DEFAULTS['monthly'])[lang]
            token = gwc.link_token(SECRETS.data.get('linkSecret', ''), sid, st['portalNonce']) if SECRETS.configured and st.get('portalNonce') else ''
            values = {'student': st['name'], 'group': ', '.join([STORE.row('groups', e['groupId'])['name'] for e in file['enrollments'] if STORE.row('groups', e['groupId'])]),
                      'date': center.date.today().isoformat(), 'amount': qs.get('amount', ''),
                      'balance': str(round(sum((e.get('money') or {}).get('balance', 0) for e in file['enrollments']), 2)),
                      'center': str(cfg.get('systemName') or 'Hessa'), 'link': SECRETS.url + '/t/' + token if token else ''}
            for key, value in values.items():
                text = text.replace('{' + key + '}', value)
            return self.send(200, {'to': center.D.wa_number(st.get('parentMobile')), 'text': text})
        if action == 'today':
            self.need('door.use', 'groups.view', 'attendance.mark')
            d = center.D.as_date(qs.get('date')) or center.date.today()
            return self.send(200, {'date': d.isoformat(), 'sessions': center.sessions_on(STORE, d, sc)})
        if action == 'find':
            self.need('door.use', 'students.view')
            out = center.find_students(STORE, qs.get('q', ''), sc)
            return self.send(200, [self.contact_filter(s) for s in out])
        if action == 'card':
            self.need('door.use', 'students.view')
            card = center.door_card(STORE, qs.get('id', ''), None, sc)
            card['student'] = self.contact_filter(card['student'])
            card['shift'] = center.my_shift(STORE, self.u['id'], NODE.id)
            return self.send(200, card)
        if action == 'roster':
            self.need('door.use', 'groups.view', 'attendance.mark')
            r = center.roster(STORE, qs.get('session', ''), sc)
            for row in r['rows']:
                row['student'] = self.contact_filter(row['student'])
            return self.send(200, r)
        if action == 'student':
            self.need('students.view')
            f = center.student_file(STORE, qs.get('id', ''), sc)
            f['student'] = {k: v for k, v in self.contact_filter(f['student']).items() if k not in ('portalHash', 'portalNonce')}
            f['parentLink'] = {'has': bool(f['student'] and STORE.row('students', f['student']['id']).get('portalHash')),
                               'gateway': SECRETS.configured, 'canMake': self.can('messages.send')}
            if not self.can('money.view', 'money.collect', 'door.use') and self.u['scopes'] is None:
                f['payments'] = []
            return self.send(200, f)
        if action == 'risk':
            self.need('followup.view')
            out = center.risk_list(STORE, sc)
            for r in out:
                r['student'] = self.contact_filter(r['student'])
            return self.send(200, out)
        if action == 'shift':
            sh = center.my_shift(STORE, self.u['id'], NODE.id)
            sid = qs.get('id') or (sh or {}).get('id')
            if not sid:
                return self.send(200, {'shift': None})
            s = STORE.row('shifts', sid)
            if s and s.get('userId') != self.u['id']:
                self.need('shifts.manage', 'money.view')
            return self.send(200, center.shift_summary(STORE, sid))
        if action == 'shifts':
            self.need('shifts.manage', 'money.view')
            frm = qs.get('from') or (center.date.today() - center.timedelta(days=31)).isoformat()
            rows = STORE.rows('shifts', "substr(opened_at,1,10)>=? OR status='open'", (frm,))
            return self.send(200, sorted(rows, key=lambda r: r.get('openedAt') or '', reverse=True))
        if action == 'money':
            self.need('money.view')
            frm, to = qs.get('from') or center.date.today().isoformat(), qs.get('to') or center.date.today().isoformat()
            return self.send(200, {'payments': STORE.rows('payments', 'date>=? AND date<=?', (frm, to), sc),
                                   'expenses': STORE.rows('expenses', 'date>=? AND date<=?', (frm, to), sc)})
        if action == 'settlements':
            self.need('settlements.view')
            return self.send(200, center.settlements(STORE, qs.get('ym', ''), sc))
        if action == 'school':
            self.need('reports.view', 'settlements.view')
            return self.send(200, center.school_statement(STORE, qs.get('groupId', ''), qs.get('ym', ''), sc))
        if action == 'reports':
            self.need('reports.view')
            return self.send(200, center.reports(STORE, qs.get('ym', ''), sc))
        if action == 'dashboard':
            self.need('overview.view')
            out = center.dashboard(STORE, sc)
            if not self.can('money.view', 'reports.view'):
                for k in ('todayMoney', 'todayTotal', 'monthMoney', 'monthExpenses', 'owed', 'moneyTrend'):
                    out.pop(k, None)
            return self.send(200, out)
        if action == 'absent':
            self.need('followup.view', 'attendance.mark', 'messages.send')
            return self.send(200, center.absentees(STORE, None, sc))
        if action == 'balances':
            self.need('money.view', 'money.collect', 'followup.view')
            return self.send(200, center.student_balances(STORE, sc))
        if action == 'advice':
            self.need('overview.view')
            return self.send(200, center.advice(STORE, sc, self.u['perms'], user_id=self.u['id'], node_id=NODE.id, system=system_status(self.u)))
        if action == 'status':  # the overview's "is everything safe?" card: only the parts this user may act on
            self.need('overview.view')
            return self.send(200, system_status(self.u))
        if action == 'exam':
            self.need('exams.view', 'marks.enter')
            r = center.exam_results(STORE, qs.get('id', ''), sc)
            for row in r['rows']:
                row['student'] = self.contact_filter(row['student'])
            return self.send(200, r)
        if action == 'clashes':
            self.need('groups.view')
            return self.send(200, center.D.clashes(STORE.rows('groups'), {r['id']: r for r in STORE.rows('rooms')}))
        self.send(404, {'error': 'Not found'})

    def state_filter(self, data):
        if 'rows' in data:
            data['rows'] = self.state_filter(data['rows'])
        if 'students' in data:
            data['students'] = [self.contact_filter(s) for s in data['students']]
        if 'teachers' in data and not self.can('contacts.view'):
            data['teachers'] = [{k: v for k, v in t.items() if k != 'mobile'} for t in data['teachers']]
        return data

    def contact_filter(self, s):
        """Parents' numbers only for people allowed to see them."""
        if not s or self.can('contacts.view'):
            return s
        return {k: v for k, v in s.items() if k not in ('mobile', 'parentMobile', 'parentMobile2')}

    def center_post(self, action, d):
        c = self.ctx()
        if action in ('sample', 'sample/delete'):
            self.need('data.import')
            self.need('users.manage')
            self.need_all_scopes()
            import sample
            if action == 'sample' and not STORE.row('settings', 'smp-centre') and STORE.counts().get('Students'):
                BACKUPS.create('pre-sample')
            return self.send(200, sample.load(c, AUTH, self.u) if action == 'sample' else sample.remove(c, AUTH, self.u))
        if action == 'portal':
            self.need('messages.send')
            if not SECRETS.configured:
                raise center.Problem('err.noGateway', 'Configure parent links first.')
            sid = str(d.get('studentId') or '')
            st = center.student_file(STORE, sid, c.scopes)['student']
            with STORE.lock:
                st = STORE.row('students', sid)
                nonce = gwc.new_nonce() if d.get('replace') or not st.get('portalNonce') else st['portalNonce']
                token = gwc.link_token(SECRETS.data['linkSecret'], sid, nonce)
                if nonce != st.get('portalNonce'):
                    row = {k: v for k, v in st.items() if k not in ('id', 'ver')}
                    row.update(portalNonce=nonce, portalHash=gwc.token_hash(token))
                    c.commit('Parent link replaced' if d.get('replace') else 'Parent link created',
                             [{'e': 'students', 'id': sid, 'op': 'put', 'ver': st['ver'], 'row': row}])
            GATE.kick()
            url = SECRETS.url + '/t/' + token   # the page the gateway serves; a #fragment never reaches the server
            phone = center.D.wa_number(st.get('parentMobile')) if self.can('contacts.view') else ''
            return self.send(200, {'url': url, 'waUrl': 'https://wa.me/' + phone + '?text=' + quote(url) if phone else ''})
        if action == 'checkin':
            return self.send(200, center.checkin(c, str(d.get('studentId')), str(d.get('sessionId')), d.get('status'), str(d.get('via') or 'code')[:10],
                                                 trial=bool(d.get('trial'))))
        if action == 'roll':
            return self.send(200, center.mark_many(c, str(d.get('sessionId')), d.get('marks') or {}))
        if action == 'session':
            return self.send(200, center.set_session_status(c, str(d.get('sessionId')), d.get('status'), d.get('topic')))
        if action == 'session/add':
            return self.send(200, center.add_session(c, str(d.get('groupId')), d.get('date'), d.get('start'), d.get('end'), d.get('topic') or ''))
        if action == 'dayoff':
            return self.send(200, center.day_off(c, d.get('date'), d.get('reason') or ''))
        if action == 'enroll':
            return self.send(200, center.enroll(c, str(d.get('studentId')), str(d.get('groupId')), d.get('from'), d.get('fee'), d.get('billFrom') or None))
        if action == 'transfer':
            return self.send(200, center.transfer(c, str(d.get('enrollmentId')), str(d.get('groupId')), d.get('from'), d.get('reason') or ''))
        if action == 'credit/move':
            return self.send(200, center.move_credit(c, str(d.get('studentId')), str(d.get('from')), str(d.get('to')), d.get('amount'), d.get('reason') or ''))
        if action == 'leave':
            return self.send(200, center.end_enrollment(c, str(d.get('enrollmentId')), d.get('to'), d.get('reason') or ''))
        if action == 'shift/open':
            return self.send(200, center.open_shift(c, d.get('opening')))
        if action == 'shift/close':
            return self.send(200, center.close_shift(c, str(d.get('shiftId')), d.get('counted'), d.get('reason') or ''))
        if action == 'pay':
            return self.send(200, center.pay(c, d))
        if action == 'pay/many':
            return self.send(200, center.pay_many(c, d))
        if action == 'void':
            return self.send(200, center.void_payment(c, str(d.get('id')), d.get('reason')))
        if action == 'expense':
            return self.send(200, center.add_expense(c, d))
        if action == 'expense/void':
            return self.send(200, center.void_expense(c, str(d.get('id')), d.get('reason')))
        if action == 'followup':
            return self.send(200, center.log_followup(c, d))
        if action == 'marks':
            return self.send(200, center.save_marks(c, str(d.get('examId')), d.get('items') or []))
        if action == 'settlement/approve':
            return self.send(200, center.approve_settlement(c, str(d.get('teacherId')), str(d.get('ym'))))
        if action == 'import':
            return self.send(200, center.import_commit(c, d.get('rows') or [], bool(d.get('enrol', True))))
        if action == 'timetable/check':
            self.need('groups.manage')
            return self.send(200, center.timetable_problems(STORE, d.get('ops') or []))
        self.send(404, {'error': 'Not found'})

    # ------------------------------------------------------------ conflicts
    def conflict_list(self):
        out = STORE.conflicts()
        who = {}
        for c in out:
            if c['kind'] == 'conflict':
                for fld, entries in c['detail'].items():
                    for e in entries:
                        k = (e['origin'], e['cseq'])
                        if k not in who:
                            who[k] = JOURNAL.describe(*k)
                        e['by'] = who[k]
            elif c['kind'] == 'deleted-edit':
                c['delete_by'] = JOURNAL.describe(*c['detail']['delete'])
                c['edits_by'] = [JOURNAL.describe(*x) for x in c['detail']['edits'][:10]]
        return out

    def resolve_conflict(self, d):
        """The administrator decides: one value for a field, keep a record deleted, or bring it back."""
        from store import ENTITIES
        entity, rid, action = d.get('entity'), str(d.get('id') or ''), d.get('action')
        if entity not in ENTITIES:
            raise BadRequest('Unknown record type')
        table = ENTITIES[entity][0]
        with STORE.lock:
            r = STORE.conn.execute(f'SELECT * FROM {table} WHERE id=?', (rid,)).fetchone()
        if not r:
            raise BadRequest('Record not found')
        row = STORE._row_js(entity, r)
        ver = row.pop('ver')
        if action == 'value':
            field = d.get('field')
            row[field] = d.get('value')
            if field == 'name' and entity in ('students', 'teachers'):
                row['nameKey'] = center.D.key_text(row['name'])      # the search key follows the chosen name
            op = {'e': entity, 'id': rid, 'op': 'put', 'row': row, 'ver': ver, 'resolve': [field]}
            label = f'Conflict resolved: {field}'
        elif action == 'keep-deleted':
            op = {'e': entity, 'id': rid, 'op': 'del', 'resolve': True}
            label = 'Conflict resolved: keep deleted'
        elif action == 'restore':
            op = {'e': entity, 'id': rid, 'op': 'put', 'row': row}
            label = 'Conflict resolved: record restored'
        else:
            raise BadRequest('Unknown action')
        res = STORE.commit(self.user, self.ip, label, [op], force=action != 'value', user_id=self.u['id'])
        AUTH.log(self.user, self.ip, 'conflict-resolved', f'{entity} {rid}', label)
        return res

    # ------------------------------------------------------------ files
    def upload(self, name):
        ext = os.path.splitext(name)[1].lower()
        if ext not in UPLOAD_EXT:
            raise BadRequest(f'File type {ext or "(none)"} is not allowed')
        data = self.body(int(CFG['max_upload_mb']) * 1048576)
        if not data:
            raise BadRequest('Empty file')
        # content-addressed: the name is the SHA-256 of the content, so the same file is stored once and every PC can check its copy
        src, _ = store_bytes(data, ext, self.user, self.ip, self.u['id'])
        log.info('UPLOAD %s (%s) %s -> %s %d bytes', self.user, self.ip, name, src, len(data))
        self.send(200, {'src': src, 'size': len(data)})

    def serve_static(self, rel):
        """The program's own web pages: from inside Hessa.exe when installed, else from the program folder.
        Only index.html and files inside css/, js/ and lib/ - never anything else of the program folder (data, keys)."""
        rel = unquote(rel).replace('\\', '/')
        parts = rel.split('/')
        ext = os.path.splitext(rel)[1].lower()
        if (any(x in ('', '.', '..') or ':' in x for x in parts) or ext not in STATIC_EXT
                or not (rel == 'index.html' or len(parts) > 1 and parts[0] in ('css', 'js', 'lib', 'fonts'))):
            return self.send(404, {'error': 'File not found'})
        if ASSETS is not None:
            data = ASSETS.get(rel)
        else:
            path = os.path.join(ROOT, *parts)
            data = None
            if os.path.isfile(path):
                with open(path, 'rb') as f:
                    data = f.read()
        if data is None:
            return self.send(404, {'error': 'File not found'})
        ctype = TYPES.get(ext) or mimetypes.guess_type(rel)[0] or 'application/octet-stream'
        return self.send(200, data, ctype, {'Cache-Control': 'no-cache'})

    def serve_file(self, base, rel, upload=False, src=None):
        base = os.path.realpath(base)
        path = os.path.realpath(os.path.join(base, unquote(rel)))
        if not path.startswith(base + os.sep) or not os.path.isfile(path):
            if upload and src and STORE.file_info(unquote(src)) and os.path.splitext(path)[1].lower() in IMAGE_EXT:
                # known file that has not been copied from another PC yet - never cached
                return self.send(200, PLACEHOLDER, 'image/svg+xml', {'Cache-Control': 'no-store'})
            if upload and src and STORE.file_info(unquote(src)):
                return self.send(404, {'error': 'This file is still being copied from another PC. Try again in a minute.'})
            return self.send(404, {'error': 'File not found'})
        ext = os.path.splitext(path)[1].lower()
        if upload and ext not in UPLOAD_EXT:
            return self.send(404, {'error': 'File not found'})
        ctype = TYPES.get(ext) or mimetypes.guess_type(path)[0] or 'application/octet-stream'
        headers = {'Cache-Control': 'public, max-age=31536000, immutable'} if upload else {'Cache-Control': 'no-cache'}
        if upload and ext not in INLINE_EXT:
            headers['Content-Disposition'] = 'attachment'
        with open(path, 'rb') as f:
            self.send(200, f.read(), ctype, headers)


class Server(ThreadingHTTPServer):
    allow_reuse_address = os.name != 'nt'  # Windows: reuse would let a second copy share the port silently; elsewhere it only skips TIME_WAIT
    daemon_threads = True


def main(background=False):
    port = int(CFG['port'])
    if not INSTANCE:
        print('The system is already running on this PC. Opening it in the browser.')
        if not background:
            webbrowser.open(f'http://localhost:{port}/')
        return
    try:
        httpd = Server((CFG['host'], port), Handler)
    except OSError:
        print(f'Port {port} is already in use - the system is probably already running. Opening it in the browser.')
        if not background:  # a second start (e.g. the desktop icon while it runs in the background) just opens it
            webbrowser.open(f'http://localhost:{port}/')
        return

    try:
        if STORE.counts().get('Students'):
            BACKUPS.create('startup')
    except Exception as e:
        say('Startup backup failed: ' + str(e))
    BACKUPS.start()
    SYNC.start()
    GATE.start()

    print('=' * 64)
    print(' Hessa is running')
    print(f' This PC:        http://localhost:{port}/')
    for u in lan_urls(port):
        print(f' Other PCs:      {u}')
    print(f' This PC:        "{NODE.name}" ({NODE.role}, id {NODE.id}), sync port {SYNC.port}')
    print(f' Data folder:    {DATA_DIR}')
    print(f' Backups folder: {BACKUPS.dir}')
    if not AUTH.has_users():
        print(' FIRST START: open http://localhost:%d/ on THIS PC to create the' % port)
        print('              administrator account (not possible from other PCs).')
    print(f' Version {VERSION} - {COPYRIGHT}')
    print(' Keep this window open. Close it to stop the system.')
    print('=' * 64, flush=True)
    say('Server started')
    if CFG.get('open_browser', True) and not background:
        threading.Timer(0.8, lambda: webbrowser.open(f'http://localhost:{port}/')).start()
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        GATE.stop()
        SYNC.shutdown()
        JOURNAL.flush_activity()
        say('Server stopped')


if __name__ == '__main__':
    main()
