"""Program version and owner. The installer build reads VERSION from here (tools/build_windows.py)."""
VERSION = '1.2.0'
PRODUCT = 'Hessa'
DEVELOPER = 'Mohamed Fawzy'
COPYRIGHT = f'© 2026 {DEVELOPER}. All rights reserved.'
LICENSE_NOTE = 'Licensed for internal use by the company that installed it. Copying, changing or reselling it is not allowed.'

# the seller's WhatsApp number for the renewal and password-recovery buttons. The repository is public, so the real
# number is never written here: the build puts it into _vendor.py (from the GitHub secret HESSA_VENDOR_WHATSAPP, see
# tools/build_windows.py), and a copy run from the source has no button.
try:
    from _vendor import VENDOR_WHATSAPP  # noqa: F401 - generated by the build, never committed
except ImportError:
    VENDOR_WHATSAPP = ''


def wa_international(number):
    """01xxxxxxxxx (how Egyptians write it) -> 201xxxxxxxxx (what wa.me needs); '' for anything that is not a mobile."""
    d = ''.join(c for c in str(number or '') if c.isdigit())
    if d.startswith('00'):
        d = d[2:]
    if d.startswith('01') and len(d) == 11:
        d = '2' + d
    return d if d.startswith('201') and len(d) == 12 else ''
