"""Program version and owner. The installer build reads VERSION from here (tools/build_windows.py)."""
import re
VERSION = '1.4.1'
PRODUCT = 'Hessa'
DEVELOPER = 'Mohamed Fawzy'
COPYRIGHT = f'© 2026 {DEVELOPER}. All rights reserved.'
LICENSE_NOTE = 'Licensed for internal use by the company that installed it. Copying, changing or reselling it is not allowed.'

# the seller's WhatsApp number for the renewal and password-recovery buttons. The repository is public, so the real
# number is never written here: the build puts it into _vendor.py (from the GitHub secret HESSA_VENDOR_WHATSAPP, see
# tools/build_windows.py), and a copy run from the source has no button.
try:
    from _vendor import VENDOR_WHATSAPP  # noqa: F401 - generated by the build, never committed
except ImportError:
    VENDOR_WHATSAPP = ''
try:
    from _vendor import SERVICE_URL  # noqa: F401 - the seller's "Hessa online" gateway (GitHub secret HESSA_SERVICE_URL)
except ImportError:
    SERVICE_URL = ''


def service_url(url):
    """https://name.workers.dev (no path, no slash at the end), or '' for anything else."""
    url = str(url or '').strip().rstrip('/')
    ok = re.fullmatch(r'https://[A-Za-z0-9.-]+(:\d+)?', url) or re.fullmatch(r'http://(127\.0\.0\.1|localhost)(:\d+)?', url)   # tests: this PC
    return url if ok else ''


def wa_international(number):
    """01xxxxxxxxx (how Egyptians write it) -> 201xxxxxxxxx (what wa.me needs); '' for anything that is not a mobile."""
    d = ''.join(c for c in str(number or '') if c.isdigit())
    if d.startswith('00'):
        d = d[2:]
    if d.startswith('01') and len(d) == 11:
        d = '2' + d
    return d if d.startswith('201') and len(d) == 12 else ''
